### ISSUE TITLE
Teselating sometimes has a NPE

### ISSUE THREAD

**Issue by Darkhax** [Darkhax-Minecraft/GYTH#9]
```
Stacktrace:
    at net.minecraft.util.ResourceLocation.func_177516_a(SourceFile:30)
    at net.minecraft.util.ResourceLocation.<init>(SourceFile:21)
    at net.darkhax.gyth.api.GythApi.getTier(GythApi.java:123)
    at net.darkhax.gyth.tileentity.TileEntityModularTank.getTier(TileEntityModularTank.java:64)
    at net.darkhax.gyth.blocks.BlockTank.getExtendedState(BlockTank.java:104)
```

http://pastebin.com/mEZKk6K3

**Comment by Gunner76th** [comment]
[crash-2017-03-20_17.46.53-client.txt](https://github.com/Darkhax-Minecraft/GYTH/files/856589/crash-2017-03-20_17.46.53-client.txt)
